name: Build Python Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Push changes
      uses: actions-go/push@v1
      with:
        author-email: elyseekevin49@gmail.com
        author-name: ELYSEE-01
        create-commit: true
        commit-message: "Commit changes from the auto-formatting action"
